endpoints:
  login: 'https://account.bellmedia.ca/api/login/v2.1'
  content_packages: 'https://capi.9c9media.com/destinations/crave_atexace/platforms/desktop/contents/{title_id}/contentpackages'
  contents: 'https://capi.9c9media.com/destinations/crave_atexace/platforms/desktop/contents/{title_id}'
  manifest: 'https://capi.9c9media.com/destinations/crave_atexace/platforms/desktop/playback/contents/{title_id}/contentpackages/{package_id}/manifest.mpd'
  srt: 'https://capi.9c9media.com/destinations/crave_atexace/platforms/desktop/playback/contents/{title_id}/contentpackages/{package_id}/manifest.srt'
  license_wv: 'https://license.9c9media.ca/widevine'
  license_pr: 'https://license.9c9media.ca/playready'

headers:
  authorization: 'Basic Y3JhdmUtYW5kcm9pZDpkZWZhdWx0'  ## Used on android phones to log in
