needs_auth: true

endpoints:
  content_packages: 'https://capi.9c9media.com/destinations/ctv_hub/platforms/desktop/contents/{title_id}/contentpackages'
  contents: 'https://capi.9c9media.com/destinations/ctv_hub/platforms/desktop/contents/{title_id}'
  manifest: 'https://capi.9c9media.com/destinations/ctv_hub/platforms/desktop/contents/{title_id}/contentpackages/{package_id}/manifest.mpd?filter=25'
  license: 'https://license.9c9media.ca/widevine'
