endpoints:
  content: https://therokuchannel.roku.com/api/v2/homescreen/content/https%3A%2F%2Fcontent.sr.roku.com%2Fcontent%2Fv1%2Froku-trc%2F
  vod: https://therokuchannel.roku.com/api/v3/playback
  token: https://therokuchannel.roku.com/api/v1/csrf
  search: https://therokuchannel.roku.com/api/v1/search